package com.example.recipeapp.models

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

class RecipeDetailModel(
    val image: String,
    val title: String,
    val description: String,
    val preparationTime: Int) {
    var isFavorite by mutableStateOf(false)
}

val recipeDetailDummies = listOf(
    RecipeDetailModel("", "Pizza", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi iaculis, augue sed auctor viverra, quam elit placerat ex, venenatis tempus diam ex vel purus. Maecenas ultrices ultricies eros, rutrum gravida lectus pulvinar sed. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet nibh vel quam convallis posuere eget at est. Vivamus non purus non odio bibendum congue. Praesent fringilla nunc sem, a convallis sapien blandit et. Aliquam hendrerit risus odio, id tempus nulla posuere in. Suspendisse eu faucibus tellus. Vivamus ut arcu nec erat laoreet dignissim eu at urna. Ut posuere maximus velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.", 10),
    RecipeDetailModel("", "Chicken", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi iaculis, augue sed auctor viverra, quam elit placerat ex, venenatis tempus diam ex vel purus. Maecenas ultrices ultricies eros, rutrum gravida lectus pulvinar sed. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet nibh vel quam convallis posuere eget at est. Vivamus non purus non odio bibendum congue. Praesent fringilla nunc sem, a convallis sapien blandit et. Aliquam hendrerit risus odio, id tempus nulla posuere in. Suspendisse eu faucibus tellus. Vivamus ut arcu nec erat laoreet dignissim eu at urna. Ut posuere maximus velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.", 10),
    RecipeDetailModel("", "Heart Pizza", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi iaculis, augue sed auctor viverra, quam elit placerat ex, venenatis tempus diam ex vel purus. Maecenas ultrices ultricies eros, rutrum gravida lectus pulvinar sed. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet nibh vel quam convallis posuere eget at est. Vivamus non purus non odio bibendum congue. Praesent fringilla nunc sem, a convallis sapien blandit et. Aliquam hendrerit risus odio, id tempus nulla posuere in. Suspendisse eu faucibus tellus. Vivamus ut arcu nec erat laoreet dignissim eu at urna. Ut posuere maximus velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.", 10),
    RecipeDetailModel("", "Happy Pizza", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi iaculis, augue sed auctor viverra, quam elit placerat ex, venenatis tempus diam ex vel purus. Maecenas ultrices ultricies eros, rutrum gravida lectus pulvinar sed. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet nibh vel quam convallis posuere eget at est. Vivamus non purus non odio bibendum congue. Praesent fringilla nunc sem, a convallis sapien blandit et. Aliquam hendrerit risus odio, id tempus nulla posuere in. Suspendisse eu faucibus tellus. Vivamus ut arcu nec erat laoreet dignissim eu at urna. Ut posuere maximus velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.", 10),
    RecipeDetailModel("", "Sad Pizza", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi iaculis, augue sed auctor viverra, quam elit placerat ex, venenatis tempus diam ex vel purus. Maecenas ultrices ultricies eros, rutrum gravida lectus pulvinar sed. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet nibh vel quam convallis posuere eget at est. Vivamus non purus non odio bibendum congue. Praesent fringilla nunc sem, a convallis sapien blandit et. Aliquam hendrerit risus odio, id tempus nulla posuere in. Suspendisse eu faucibus tellus. Vivamus ut arcu nec erat laoreet dignissim eu at urna. Ut posuere maximus velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.", 10)
)

val recipeDetailDummy = RecipeDetailModel("", "Pizza", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi iaculis, augue sed auctor viverra, quam elit placerat ex, venenatis tempus diam ex vel purus. Maecenas ultrices ultricies eros, rutrum gravida lectus pulvinar sed. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet nibh vel quam convallis posuere eget at est. Vivamus non purus non odio bibendum congue. Praesent fringilla nunc sem, a convallis sapien blandit et. Aliquam hendrerit risus odio, id tempus nulla posuere in. Suspendisse eu faucibus tellus. Vivamus ut arcu nec erat laoreet dignissim eu at urna. Ut posuere maximus velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.", 10)